### ISSUE TITLE
More icons request

### ISSUE THREAD

**Issue by coderex96** [scoute-dich/Blue-Minimal#11]
<item component="ComponentInfo{cm.aptoide.pt/com.aptoide.amethyst.MainActivity}" drawable="cm_aptoide_pt_com_aptoide_amethyst_MainActivity"/>

<item component="ComponentInfo{pt.aptoide.backupapps/pt.aptoide.backupapps.MainActivity}" drawable="pt_aptoide_backupapps_pt_aptoide_backupapps_MainActivity"/>

<item component="ComponentInfo{nextapp.atlas/nextapp.atlas.ui.MainBrowserActivity}" drawable="nextapp_atlas_nextapp_atlas_ui_MainBrowserActivity"/>

<item component="ComponentInfo{ru.meefik.busybox/ru.meefik.busybox.MainActivity}" drawable="ru_meefik_busybox_ru_meefik_busybox_MainActivity"/>

<item component="ComponentInfo{com.piriform.ccleaner/com.piriform.ccleaner.ui.activity.MainActivity}" drawable="com_piriform_ccleaner_com_piriform_ccleaner_ui_activity_MainActivity"/>

<item component="ComponentInfo{org.csploit.android/org.csploit.android.MainActivity}" drawable="org_csploit_android_org_csploit_android_MainActivity"/>

<item component="ComponentInfo{com.duckduckgo.mobile.android/com.duckduckgo.mobile.android.activity.DuckDuckGo}" drawable="com_duckduckgo_mobile_android_com_duckduckgo_mobile_android_activity_DuckDuckGo"/>

<item component="ComponentInfo{com.ebay.mobile/com.ebay.mobile.activities.eBay}" drawable="com_ebay_mobile_com_ebay_mobile_activities_eBay"/>

<item component="ComponentInfo{it.edo/it.edo.activities.SplashScreenActivity}" drawable="it_edo_it_edo_activities_SplashScreenActivity"/>

<item component="ComponentInfo{com.freeletics.lite/com.freeletics.activities.StartActivity}" drawable="com_freeletics_lite_com_freeletics_activities_StartActivity"/>

<item component="ComponentInfo{com.instagram.android/com.instagram.android.activity.MainTabActivity}" drawable="com_instagram_android_com_instagram_android_activity_MainTabActivity"/>

<item component="ComponentInfo{com.justeat.app.it/com.justeat.app.ui.MainActivity}" drawable="com_justeat_app_it_com_justeat_app_ui_MainActivity"/>

<item component="ComponentInfo{com.android.vending.billing.InAppBillingService.LOCK/com.android.vending.billing.InAppBillingService.LOCK.MainActivity-Original}" drawable="com_android_vending_billing_InAppBillingService_LOCK_com_android_vending_billing_InAppBillingService_LOCK_MainActivity-Original"/>

<item component="ComponentInfo{net.pluservice.myCicero/net.pluservice.myCicero.MainActivity}" drawable="net_pluservice_myCicero_net_pluservice_myCicero_MainActivity"/>

<item component="ComponentInfo{air.nn.mobile.app.main/air.nn.mobile.app.main.AppEntry}" drawable="air_nn_mobile_app_main_air_nn_mobile_app_main_AppEntry"/>

<item component="ComponentInfo{org.torproject.android/org.torproject.android.OrbotMainActivity}" drawable="org_torproject_android_org_torproject_android_OrbotMainActivity"/>

<item component="ComponentInfo{com.paypal.android.p2pmobile/com.paypal.android.p2pmobile.startup.activities.StartupActivity}" drawable="com_paypal_android_p2pmobile_com_paypal_android_p2pmobile_startup_activities_StartupActivity"/>

<item component="ComponentInfo{dp.ws.popcorntime/se.popcorn_time.mobile.ui.MainActivity}" drawable="dp_ws_popcorntime_se_popcorn_time_mobile_ui_MainActivity"/>

<item component="ComponentInfo{posteitaliane.posteapp.apppostepay/posteitaliane.posteapp.apppostepay.SplashActivity}" drawable="posteitaliane_posteapp_apppostepay_posteitaliane_posteapp_apppostepay_SplashActivity"/>

<item component="ComponentInfo{com.lynxspa.prontotreno/com.lynxspa.prontotreno.SplashActivity}" drawable="com_lynxspa_prontotreno_com_lynxspa_prontotreno_SplashActivity"/>

<item component="ComponentInfo{com.waze/com.waze.FreeMapAppActivity}" drawable="com_waze_com_waze_FreeMapAppActivity"/>

<item component="ComponentInfo{cn.wps.moffice_eng/cn.wps.moffice.documentmanager.PreStartActivity}" drawable="cn_wps_moffice_eng_cn_wps_moffice_documentmanager_PreStartActivity"/>

**Comment by scoute-dich** [comment]
Can you post the content of the xmf-file in the BM_IconRequest folder on your sd-card? Otherwise I can't help...

**Comment by coderex96** [comment]
https://www.dropbox.com/s/irwh5dfe63p9l0z/BM_Icon-Request.tar.gz?dl=0

**Comment by scoute-dich** [comment]
Thanks,

will add them in next release. Probably July/August (much to do at work at the moment).

**Comment by scoute-dich** [comment]
Done. Will be in next update.
