### ISSUE TITLE
Question: Why is the permission "Change system settings" needed?

### ISSUE THREAD

**Issue by conrad-heimbold** [scoute-dich/Blue-Minimal#16]
Hello, I just have one question: why is the permission android.permission.WRITE_SETTINGS needed? All the other theme apps for   CyanogenMod (e.g. Twelfe, Ameixa) don't seem to need it. That permission should be used wisely, as far as I know, because of security. Thanks for an answer!

**Comment by scoute-dich** [comment]
It is needed to cange default ringtone and notification sound.

**Comment by scoute-dich** [comment]
Perhaps I should add an explanation dialog in next update. Also with the possibility to never show this permission request for users who don't want to change their sounds through the app?

**Comment by conrad-heimbold** [comment]
I always thought that the CyanogenMod theme app overs a kind of abstraction layer for themes, ringtones, etc.; in the following way: 
The theming apps do not directly require those permissions, but instead get those permissions delegated via the CyanogenMod theming app which governs the delegation. Isn't that the case? Please correct me if I'm wrong...

**Comment by scoute-dich** [comment]
You are right. Normally these permissions are not needed. But I personally wanted the possibility to change the default ringtone and notification sound from within my theme.

And there is the problem. For the theme I can only save one ringtone, one notification tone and one alarm sound in the assets folder. This folder is read only. So I can't copy another file in these folders. The only solution I found is to change system settings.

The second solution, I used for changing the default alarm sound, is copying the files to sd card (in alarms, notifications or ringtone folder). But then you have to reboot the phone to rescan media and then change the desired tone in the system settings.

Perhaps you have an other idea. I'm always open to improvements. I learned all I'm doing by do it yourself and I'm willingly to learn...

**Comment by scoute-dich** [comment]
With next update I make the permission optional. It will be deactivated by default. You are right: not all users use this functionality, so it should be deactivated. Thanks for the question.

Here is the relevant commit:
https://github.com/scoute-dich/Blue-Minimal/commit/7d5ecb902b60e363ea8ac27b65d748d646f43276

**Comment by conrad-heimbold** [comment]
Thanks for your fast answers and your commit!
