### ISSUE TITLE
Twidere Icon

### ISSUE THREAD

**Issue by amilopowers** [scoute-dich/Blue-Minimal#17]
Thank you very much for your great theme!

Could you please create an icon for the popular Twiiter app "Twidere"? http://twidere.mariotaku.org/

**Comment by scoute-dich** [comment]
You must go to the right tab of the application, press the app icon and the choose the "Twidre"" app. The you can create a Zip-file, which will be stored on your sd-card. Upload the Zip-file here. ThanI can create the icon.

Greetings
Gaukler Faun

**Comment by amilopowers** [comment]
Oh I didn't know that it is that easy....
[Icon_request_16-08-18_23-29.zip](https://github.com/scoute-dich/Blue-Minimal/files/425936/Icon_request_16-08-18_23-29.zip)

**Comment by scoute-dich** [comment]
Ok, I will make it in the next days.

**Comment by scoute-dich** [comment]
[theme-release.zip](https://github.com/scoute-dich/Blue-Minimal/files/438869/theme-release.zip)

Hi,

I made the icon. Since I don't want to release an update because of one icon, I attaches the apk in the zip-file. So you can manually install it.

I hope it's ok. If there are further questions, just ask.

Regards
Gaukler Faun

**Comment by amilopowers** [comment]
Thank you very much! I appreciate that!
I have attached some more. I would love if you could create those as well.
Thank you very much! 
Do you take donations?

[Uploading Icon_request_16-08-26_13-06.zip…]()

**Comment by scoute-dich** [comment]
Hi,

I'm currently in vacation, but I will add your icons as soon as possible. If you want you can donate via paypal. I've added a button on the project site.

Regards
Gaukler Faun

**Comment by scoute-dich** [comment]
added
