### ISSUE TITLE
Icon for ProtonMail and Slack

### ISSUE THREAD

**Issue by artur9010** [scoute-dich/Blue-Minimal#18]

**Comment by scoute-dich** [comment]
Can you please make a icon request in the right tab of the app and attach the zip file here?

**Comment by artur9010** [comment]
[Icon_request_16-11-26_17-50 - kopiuj.zip](https://github.com/scoute-dich/Blue-Minimal/files/614346/Icon_request_16-11-26_17-50.-.kopiuj.zip)

Sure :)

**Comment by scoute-dich** [comment]
Thanks for the ZIP and sorry for the late reply. I'm busy at the moment, so it could take a couple of time, but the icons will be added in next update.

**Comment by scoute-dich** [comment]
Update released. Should be available in a few days. If there are problems just report them.
