### ISSUE TITLE
Does not work on CM14

### ISSUE THREAD

**Issue by baldurmen** [scoute-dich/Blue-Minimal#19]
I recently installed CM14 and the cyanogenmod theme app seems to have disappeared.

I can select the background via the blue minimal app, but neither ringtones nor icons work.

**Comment by scoute-dich** [comment]
I know. There is no theme manager implemented in cm14 until now. So no theme will work. We just have to wait... I have the same problem running cm14.1.

I have released an update before two days, but it's not now available on f-droid. Just wait a few more days. With this update you can set ring and notification sounds in the "sounds tab" easily by long pressing. The system settings will open and there you can set the preferred sound.

You can also copy a preferred alarm sound in the "alarm folder" on your sdcard and then change the alarm sound in the settings of your alarm app (there are no system settings for alarm). 

So at the moment no chance of changing icons.

**Comment by scoute-dich** [comment]
Since I have the same problem (running Android 7.1.1) I added Apex launcher theme support in version 4.4. So it's possible to apply the icons in all launchers which have Apex theme support (Nova, Apex, Action Launcher, ...). That's all I can do for the moment.

Regards
Gaukler Faun
