### ISSUE TITLE
Icon Pack not in Substratum Theme?

### ISSUE THREAD

**Issue by ejtejada** [scoute-dich/Blue-Minimal#30]
Hello scoute-dich,
I noticed you have the substratum version at:
https://github.com/scoute-dich/Minimal
However, it looks like that icon pack is much smaller, and going for square icon look instead. Are you abandoning this cicular icon pack in favor of your new square ones?

**Comment by scoute-dich** [comment]
Yes I abandoned this project. I moved on and I'm using now substratum theme. I don't want to publish it, since I#ve no time to maintain it. There are so many user requests for icons from apps I'll never use. I just publish it on Github, if anybody wants to make a bigger thing of it.
